spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.3.98:8848

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"